### PR TITLE
Updating Symmer Codebase Documentation following Google Styles

### PR DESCRIPTION
**Pull request by devilkiller-ag**
The Symmer codebase is completely documented, but in an unofficial style. I am formatting the documentation into the [Google style](https://google.github.io/styleguide/pyguide.html). Creating this PR for issue #139. The Formatting is not completed yet, but creating this PR to keep in loop with maintainer.

### CODE REVIEW

**Comment by AlexisRalli** [comment]
@devilkiller-ag This is exactly what we wanted. The updates looks great

**Comment by devilkiller-ag** [comment]
Thanks @AlexisRalli, I will complete the work soon.

**Comment by devilkiller-ag** [comment]
@AlexisRalli, in the file [qubit_subspace_manager.py](https://github.com/UCL-CCS/symmer/blob/main/symmer/projection/qubit_subspace_manager.py), on line 190 it is mentioned `Project additional operators consistently with respect to the Hamiltonian.`. But the function in which it is written projects quantum state instead of operator. Should I rectify it?

**Comment by AlexisRalli** [comment]
> @AlexisRalli, in the file [qubit_subspace_manager.py](https://github.com/UCL-CCS/symmer/blob/main/symmer/projection/qubit_subspace_manager.py), on line 190 it is mentioned `Project additional operators consistently with respect to the Hamiltonian.`. But the function in which it is written projects quantum state instead of operator. Should I rectify it?

@devilkiller-ag You are correct. The function `project_auxiliary_state` should say: "Project quantum state consistently with respect to the Hamiltonian" in its description.

**Comment by devilkiller-ag** [comment]
Sure @AlexisRalli

**Comment by AlexisRalli** [comment]
@devilkiller-ag I will look into your PR by Monday!

**Review by AlexisRalli — APPROVED** [review]

**Comment by AlexisRalli** [comment]
> @AlexisRalli any updates?

@devilkiller-ag Looks good! Just running tests that should pass and then I'll merge and close this PR. Congrats on completing this bounty

**Comment by devilkiller-ag** [comment]
Thanks @AlexisRalli , Feel free to contact me if further modifications are needed in future.

**Pull request merged**
